# Generated by Django 3.1.1 on 2020-10-11 09:32

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('raw_text', models.TextField(default='___ raw text ___')),
                ('create_location', models.JSONField(null=True)),
                ('requirement_type', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Remove'), (1, 'Pending'), (2, 'Doing'), (3, 'Done')], max_length=7, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Not know'), (1, 'Female'), (2, 'Male'), (3, 'Other')], max_length=7)),
                ('avatar', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_raw_text', models.TextField(default='___ first your text ___')),
                ('create_time', models.TimeField(auto_now_add=True, null=True)),
                ('last_edit_time', models.TimeField(auto_now=True, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('expire_time', models.TimeField(null=True)),
                ('location', models.JSONField(null=True)),
                ('person', models.JSONField(null=True)),
                ('organize', models.JSONField(null=True)),
                ('priority', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Normality'), (1, 'Priority')], max_length=3, null=True)),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Remove'), (1, 'Pending'), (2, 'Doing'), (3, 'Done')], max_length=7, null=True)),
                ('messsages', models.ManyToManyField(to='notes.Message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.user')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.user'),
        ),
    ]
