# Generated by Django 3.1.1 on 2020-09-27 11:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Not know'), (1, 'Female'), (2, 'Male'), (3, 'Other')], max_length=7)),
                ('avatar', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='expire_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='last_edit_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='location',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='organize',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='person',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='priority',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Normality'), (1, 'Priority')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Remove'), (1, 'Pending'), (2, 'Doing'), (3, 'Done')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
