# Generated by Django 3.1.1 on 2020-10-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201011_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='organize',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.TextField(null=True),
        ),
    ]
