# Generated by Django 3.1.1 on 2020-10-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20201011_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
