# Generated by Django 3.1.1 on 2020-10-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20201011_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
