# Generated by Django 3.1.1 on 2020-10-11 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20201011_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 10, 40, 22, 308294)),
        ),
    ]
