# Generated by Django 3.1.1 on 2020-10-11 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20201011_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 47, 54, 722122)),
        ),
        migrations.AlterField(
            model_name='task',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_edit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 47, 54, 722157)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 47, 54, 722176)),
        ),
    ]
