# Generated by Django 3.1.1 on 2020-10-11 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20201011_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='messsages',
            new_name='messages',
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 18, 14, 8, 799214)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_edit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 18, 14, 8, 799248)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 18, 14, 8, 799272)),
        ),
    ]
