# Generated by Django 3.1.1 on 2020-10-18 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20201011_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='organize',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 16, 23, 9, 667625)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_edit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 16, 23, 9, 667654)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 16, 23, 9, 667672)),
        ),
    ]
