# Generated by Django 3.1.1 on 2020-11-01 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20201101_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='requirement_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Remind'), (2, 'Update'), (3, 'Query')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 23, 29, 1, 145643)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_edit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 23, 29, 1, 145669)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 23, 29, 1, 145687)),
        ),
    ]
